Added style overriding to tableHead
SCALARA-GmbH/ui-core pull request #48
Opened 2021-12-08 16:19 UTC by olpoletaiev

## Summary 💡

## Checklist

- [ ] Added or extended tests
- [ ] Checked linter warnings
- [ ] Typed as much as possible

2021-12-08 16:30 UTC, LianeWalter approved these changes

2021-12-09 09:06 UTC, the0ffh requested changes

2021-12-10 09:17 UTC, the0ffh approved these changes

2021-12-10 09:17 UTC, the0ffh commented on core/src/components/DataTable/DataTableHead.tsx
> +  return <TableHead className={classNames(styles.root)}>{children}</TableHead>;
```suggestion
  return <TableHead className={className}>{children}</TableHead>;
```

2021-12-10 09:17 UTC, the0ffh commented on core/src/components/DataTable/DataTableHead.tsx
> +  return <TableHead className={classNames(styles.root)}>{children}</TableHead>;
you should be styling children, not \<TableHead/> in your case

2021-12-10 09:46 UTC, merged